// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var BsAsyncMonad = require("bs-async-monad/src/bsAsyncMonad.js");
var Wav$LidcoreBsWav = require("../src/wav.js");

var path;

try {
  path = Caml_array.caml_array_get(process.argv, 2);
}
catch (exn){
  console.log("Usage: wavinfo /path/to/file.wav");
  path = process.exit(1);
}

BsAsyncMonad.Callback[/* finish */31](undefined, BsAsyncMonad.Callback[/* >> */3](Wav$LidcoreBsWav.read(path), (function (info) {
            var info$1 = JSON.stringify(info, null, 2);
            console.log("Wav file info:\n" + (String(info$1) + ""));
            var partial_arg = BsAsyncMonad.Callback[/* return */0];
            return (function (param) {
                return partial_arg(/* () */0, param);
              });
          })));

/* path Not a pure module */
